# Generated by Django 2.1.1 on 2018-09-18 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unlock', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='models',
            old_name='carrier_id',
            new_name='carrier',
        ),
        migrations.RenameField(
            model_name='models',
            old_name='phone_id',
            new_name='phone',
        ),
    ]
