# Generated by Django 2.1.1 on 2018-09-18 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unlock', '0002_auto_20180918_2330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='models',
            old_name='carrier',
            new_name='Carrier',
        ),
        migrations.RenameField(
            model_name='models',
            old_name='phone',
            new_name='Phone',
        ),
    ]
