# Generated by Django 2.1.1 on 2018-09-20 23:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unlock', '0003_auto_20180918_2332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='models',
            old_name='Carrier',
            new_name='carrier',
        ),
        migrations.RenameField(
            model_name='models',
            old_name='Phone',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='info',
            name='models',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unlock.Models'),
        ),
    ]
