# Generated by Django 2.1.1 on 2018-09-22 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unlock', '0006_histories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('network', models.CharField(max_length=64)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
